name: geophys_utils
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy=1.24.3
  - gdal=3.6.2
  - affine=2.3.0
  - cartopy=0.18.0
  - matplotlib=3.7.1
  - numexpr=2.8.4
  - owslib=0.24.1
  - pyyaml=6.0
  - requests=2.29.0
  - scikit-image=0.19.3
  - scipy=1.10.1
  - shapely=2.0.1
  - unidecode=1.3.6
  - pip:
    - netCDF4==1.6.4
    - zipstream-new==1.1.8