--- 
DEBUG: True
DB_ENGINE: "Postgres"
LOGFILE: "dataset_metadata_cache.log"
LOGLEVEL: "WARNING"
SQLITE_DB_PATH: "data/dataset_metadata_cache.sqlite"
POSTGRES_SERVER: "localhost"
POSTGRES_PORT: 5432
POSTGRES_DBNAME: "dataset_metadata_cache"
POSTGRES_USER: "db_user"
POSTGRES_PASSWORD: "db_password"
LOCAL_TIMEZONE: "AEDT"