field_names:
  Obsno: {short_name: Obsno, long_name: Observation Number, database_field_name: obsno, dtype: int32, fill_value: -9999.9}
  Stationno: {short_name: Stationno, long_name: Station Number, database_field_name: STATIONNO, dtype: int64, fill_value: -999999999.9}
  Stattype: {short_name: Stattype, long_name: Station Type, database_field_name: STATIONTYPE, dtype: int8, lookup_table: STATIONTYPES, convert_keys_and_data_to_int8: True, fill_value: -99}

  Lat: {standard_name: latitude, long_name: Latitude, database_field_name: dlat, dtype: float64, units: degrees_north, fill_value: -99999.9, axis: Y}
  Long: {standard_name: longitude, long_name: Longitude, database_field_name: dlong, dtype: float64, units: degrees_east, fill_value: -99999.9, axis: X}
  Locmethod: {short_name: Locmethod, long_name: Location Method, database_field_name: LOCMETH, dtype: int8, lookup_table: LOCMETHODS, convert_keys_and_data_to_int8: True, fill_value: -99}
  Locacc: {short_name: Locacc, long_name: Location Accuracy, database_field_name: LOCACC, dtype: float32, units: m, fill_value: -99999.9}
  Locaccmethod: {short_name: Locaccmethod, long_name: Location Accuracy Method, database_field_name: LOCACCMETHOD, dtype: int8, lookup_table: ACCURACYMETHOD, fill_value: -99}

##TODO Spherical Cap Bouguer Anomaly (SCBA) include acryonm? SphericalCapBouguerAnomaly as ncname?
  Freeair: {short_name: Freeair, long_name: Spherical Cap Bouguer Anomaly, database_field_name: 'gravity.GRAV_FA07(o1.dlat, o1.ellipsoidhgt, o1.grav, o1.ellipsoidmeterhgt)', dtype: float32, units: um/s^2, fill_value: -99999.9}
  Bouguer: {short_name: Bouguer, long_name: Ellipsoidal Free, database_field_name: 'gravity.grav_BA07(o1.dlat, o1.ellipsoidhgt, o1.grav, o1.ellipsoidmeterhgt, o1.gndelevtype, o1.gndelev, o1.nvalue)', dtype: float32, units: um/s^2, fill_value: -99999.9}

  Grav: {short_name: Grav, long_name: Gravity, database_field_name: GRAV, dtype: float64, units: um/s^2, fill_value: -99999.9}
  Gravmeth: {short_name: Gravmeth, long_name: Gravity Method, database_field_name: GRAVMETH, dtype: int8, lookup_table: GRAVMETHODS, fill_value: -99}
  Gravacc: {short_name: Gravacc, long_name: Gravity Accuracy, database_field_name: GRAVACC, dtype: float32, units: um/s^2, datum: GRAVDATUM, convert_key_to_lookup_value_for_datum: True, convert_keys_and_data_to_int8: True, fill_value: -99}
  Gravdatum: {short_name: Gravdatum, long_name: Gravity Datum, database_field_name: GRAVDATUM, dtype: int8, lookup_table: GRAVDATUMS, fill_value: -99}
  Gravaccmeth: {short_name: Gravaccmeth, long_name: Gravity Accuracy Method, database_field_name: GRAVACCMETHOD, dtype: int8, lookup_table: ACCURACYMETHOD, fill_value: -99}

  Gndelev: {short_name: Gndelev, long_name: Ground Elevation, database_field_name: GNDELEV, dtype: float32, units: m, fill_value: -99999.9}
  Gndelevacc: {short_name: Gndelevacc, long_name: Ground Level Accuracy, database_field_name: GNDELEVACC, dtype: float32, units: m, fill_value: -99}
  Gndelevtype: {short_name: Gndelevtype, long_name: Ground Level Type, database_field_name: GNDELEVTYPE, dtype: int8, lookup_table: GNDELEVTYPES, convert_keys_and_data_to_int8: True, fill_value: -99}
  Gndelevdatum: {short_name: Gndelevdatum, long_name: Ground Level Datum, database_field_name: GNDELEVDATUM, dtype: int8, lookup_table: GNDELEVDATUMS, fill_value: -99}
  Gndelevmeth: {short_name: Gndelevmeth, long_name: Ground Level Method, database_field_name: GNDELEVMETH, dtype: int8, lookup_table: GNDELEVMETHODS, convert_keys_and_data_to_int8: True, fill_value: -99}
  Gndelevaccmethod: {short_name: Gndelevaccmethod, long_name: Ground Level Accuracy Method, database_field_name: GNDELEVACCMETHOD, dtype: int8, lookup_table: ACCURACYMETHOD, fill_value: -99}

  Insthgt: {short_name: Insthgt, long_name: Instrument Height, database_field_name: METERHGT, dtype: float32, units: m, fill_value: -99999.9}
  Insthgterr: {short_name: Insthgterr, long_name: Instrument Height Error, database_field_name: METERHGTERR, dtype: float32, units: m, fill_value: -99}
  Insthgtmeth: {short_name: Insthgtmeth, long_name: Instrument Height Method, database_field_name: METERHGTMETH, dtype: int8, lookup_table: GNDELEVMETHODS, convert_keys_and_data_to_int8: True, fill_value: -99}
  Insthgterrmeth: {short_name: Insthgterrmeth, long_name: Instrument Height Error Method, database_field_name: METERHGTERRMETHOD, dtype: int8, lookup_table: ACCURACYMETHOD, fill_value: -99}

  Ellipsoidinsthgt: {short_name: Ellipsoidinsthgt, long_name: Ellipsoid Instrument Height, database_field_name: ELLIPSOIDMETERHGT, dtype: float32, units: m, fill_value: -99999.9}
  Ellipsoidinsthgterr: {short_name: Ellipsoidinsthgterr, long_name: Ellipsoid Instrument Height Error, database_field_name: ELLIPSOIDMETERHGTERR, dtype: float32, unit: m, fill_value: -99999.9}
  Ellipsoidinsthgterrmethod: {short_name: Ellipsoidinsthgterrmethod, long_name: Ellipsoid Instrument Height Accuracy Method, database_field_name: ELLIPSOIDMETERHGTERRMETHOD, dtype: int8, lookup_table: ACCURACYMETHOD, fill_value: -99}

  Ellipsoidhgt: {short_name: Ellipsoidhgt, long_name: Ellipsoid Height, database_field_name: ELLIPSOIDHGT, dtype: float32, units: m, fill_value: -99999.9}
  Ellipsoidhgtacc: {short_name: Ellipsoidhgtacc, long_name: Ellipsoid Height Accuracy, database_field_name: ELLIPSOIDHGTACC, dtype: float32, units: m, fill_value: -99999.9}
  Ellipsoidhgtmeth: {short_name: Ellipsoidhgtmeth, long_name: Ellipsoid Height Method, database_field_name: ELLIPSOIDHGTMETH, dtype: int8, lookup_table: GNDELEVMETHODS, convert_keys_and_data_to_int8: True, fill_value: -99}
  Ellipsoidhgtaccmethod: {short_name: Ellipsoidhgtaccmethod, long_name: Ellipsoid Height Accuracy Method, database_field_name: ELLIPSOIDHGTACCMETHOD, dtype: int8, lookup_table: ACCURACYMETHOD, fill_value: -99}
  Ellipsoiddatum: {short_name: Ellipsoiddatum, long_name: Ellipsoid Datum, database_field_name: ELLIPSOIDHGTDATUM, dtype: int8, lookup_table: ELLIPSOIDHGTDATUM, convert_keys_and_data_to_int8: True, fill_value: -99}

  Tc: {short_name: Tc, long_name: Terrain Correction, database_field_name: TC, dtype: float32, units: um/s^2, dem: TCDEM, fill_value: -99999.9}
  Tcdensity: {short_name: Tcdensity, long_name: TC Density, database_field_name: TCDENSITY, dtype: float32, units: um/s^2, dem: TCDEM, fill_value: -99999.9}
  Tcerr: {short_name: Tcerr, long_name: TC Error, database_field_name: TCERR, dtype: float32, units: um/s^2, dem: TCDEM, fill_value: -99999.9}
  Tcmeth: {short_name: Tcmeth, long_name: TC Method, database_field_name: TCMETH, dtype: int8, lookup_table: TCMETHODS, convert_keys_and_data_to_int8: True, fill_value: -99}

  Gridflag:  {short_name: Gridflag, long_name: Grid Flag, database_field_name: GRIDFLAG, dtype: int8, lookup_table: GRIDFLAGS, fill_value: -99}
  Reliab: {short_name: Reliab, long_name: Estimation of Station Reliability, database_field_name: reliab, dtype: int8, lookup_table: RELIABILITY, fill_value: -99}
##
#
#
#










#TODO it would be nice to have some logic that checks if a value such as gndelevdatum or gravmeth are consistent for all points in a survey and create a variable level attribute, otherwise create the lookup table. However, whats more importance, consistency in structure or file size?



#  GRAVMETH

#  GRAVACCMETHOD

#  LOCMETH

#  LOCACCMETHOD

#  GNDELEVMETH

#  GNDELEVACCMETHOD

#  METERHGTMETH

#  METERHGTERRMETHOD?
#
#  TCMETH
# no tc error method

#  ELLIPSOIDHGTMETH

#  ELLIPSOIDHGTACCMETHOD
#  ELLIPSOIDMETERHGTMETH

#  ELLIPSOIDMETERHGTERRMETHOD

#  NVALUEMETH
#  NVALUEACCMETHOD
#  NONGATCERRMETHOD
#  NONGATCMETH
