# Global settings
global_settings:
  debug: false
  cache_images: true # Set this to false to get images from NCI WMS endpoints
  cache_coordinates: true # Set this to true to cache coordinates and lines on local disk
  http_compression: true # Set this to false for local use, true for remote
  compress_level: 6 # 6 = Maximum compression level
  compress_min_size: 2000 # Don't bother compressing small KML responses
  database_engine: SQLite # SQLite or Postgres
  # Define number of line segments to show across bounding box height for line sub-sampling
  line_segments_across_bbox: 50 # Maximum number of line segments to show across bounding box
  cache_root_dir: 'C:\Temp' # Root directory for disk cache (if enabled)
  #host: '0.0.0.0' # Comment this out for normal local host testing
  #http_proxy: 'http://127.0.0.1:8888' # Comment this out for normal local host testing

# Default dataset settings
default_dataset_settings:
  dataset_link: null
  filtered_point_icon_color: ff000000
  height_variable: null
  line_color: ff32cd9a
  line_width: 5
  point_color_settings: ff32cd9a
  point_field_list: null
  point_icon_href: 'http://maps.google.com/mapfiles/kml/paddle/grn-blank.png'
  point_icon_scale: 0.7
  point_labelstyle_scale: 0
  polygon_color: 1
  timestamp_detail_view: false
  wms_transparency: 50
  wms_color_range: [-350, 350]
  wms_pixel_size: 0.01
  
# Dataset settings
dataset_settings:
  ground_gravity:
    dataset_format: point
    min_polygon_bbox_width: 1.5 # maximum bounding box width for detailed display. Uses survey convex-hull polygons for anything larger.
    keyword_list: [AUS, ground digital data, gravity, geophysical survey, points]
    dataset_type_name: Ground Gravity Surveys
    netcdf_path_prefix: null #C:\Temp\Geophysics\gravity point datasets # Local directory containing files. Use null to use OPeNDAP
    point_color_settings: # Parameters for point color display defined as: (<field_name>: (<color_range_min>, <color_range_max>)) or static color
    - bouguer
    - [-500, 500]
    point_field_list: [obsno, latitude, longitude, grav, freeair, bouguer, stattype, reliab, gridflag]
    point_filter: {gridflag: Station not used in the production of GA grids.} # Dict containing field names & values to filter out
    point_icon_href: http://maps.google.com/mapfiles/kml/paddle/grn-blank.png
    point_icon_scale: 0.7
    point_labelstyle_scale: 0
    polygon_color: B30000ff # Red
    polygon_outline: 1
    protocol: opendap
    dataset_link: http://dapds00.nci.org.au/thredds/catalog/uc0/rr2_dev/axi547/ground_gravity/point_datasets/catalog.html?dataset=uc0/rr2_dev/axi547/ground_gravity/point_datasets/{netcdf_basename}
    colormap_name: rainbow
    color_count: 256
    timestamp_detail_view: true
  aem:
    dataset_format: line
    min_polygon_bbox_width: 30.0 # maximum bounding box width for detailed display. Uses survey convex-hull polygons for anything larger.
    keyword_list: [geophysics, airborne, AEM, conductivity]
    dataset_type_name: AEM Surveys
    netcdf_path_prefix: null #C:\Temp\Geophysics\AEM conductivity datasets # Local directory containing files. Use null to use OPeNDAP
    polygon_color: ff32cd9a # Bright Green
    polygon_outline: 1
    line_color: ff32cd9a
    line_width: 5
    protocol: opendap
    dataset_link: http://dapds00.nci.org.au/thredds/catalog/uc0/rr2_dev/axi547/aem/catalog.html?dataset=uc0/rr2_dev/axi547/aem/{netcdf_basename}
    height_variable: lidar # Do not set this value for 2D coordinates
    colormap_name: rainbow
    color_count: 256
    timestamp_detail_view: true
  magnetic_grids:
    dataset_format: grid
    min_polygon_bbox_width: 180.0 # maximum bounding box width for detailed display. Uses survey convex-hull polygons for anything larger.
    keyword_list: [NCI, geophysical survey, airborne digital data, magnetics, grid]
    dataset_type_name: Magnetic Survey grids
    netcdf_path_prefix: null #C:\Temp\Geophysics\magnetic grids # Local directory containing files. Use null to use OPeNDAP
    polygon_color: ffff0000 # Blue
    polygon_outline: 1
    protocol: opendap
    dataset_link: 'https://ecat.ga.gov.au/geonetwork/srv/eng/catalog.search#/metadata/{metadata_uuid}'
    colormap_name: rainbow
    color_count: 256
    timestamp_detail_view: true
    wms_layer_name: mag_tmi_anomaly
    wms_color_range: [-350, 350]
  potassium_grids:
    dataset_format: grid
    min_polygon_bbox_width: 180.0 # maximum bounding box width for detailed display. Uses survey convex-hull polygons for anything larger.
    keyword_list: [NCI, geophysical survey, airborne digital data, radiometrics, potassium, grid]
    dataset_type_name: Potassium Survey grids
    netcdf_path_prefix: null #C:\Temp\Geophysics\radiometric grids # Local directory containing files. Use null to use OPeNDAP
    polygon_color: ff808080 # Grey
    polygon_outline: 1
    protocol: opendap
    dataset_link: 'https://ecat.ga.gov.au/geonetwork/srv/eng/catalog.search#/metadata/{metadata_uuid}'
    colormap_name: rainbow
    color_count: 256
    timestamp_detail_view: true
    wms_layer_name: rad_k_conc
    wms_color_range: [0, 5]
    wms_pixel_size: 0.01
  thorium_grids:
    dataset_format: grid
    min_polygon_bbox_width: 180.0 # maximum bounding box width for detailed display. Uses survey convex-hull polygons for anything larger.
    keyword_list: [NCI, geophysical survey, airborne digital data, radiometrics, thorium, grid]
    dataset_type_name: Thorium Equivalent Survey grids
    netcdf_path_prefix: null #C:\Temp\Geophysics\radiometric grids # Local directory containing files. Use null to use OPeNDAP
    polygon_color: ffffff00 # Cyan
    polygon_outline: 1
    protocol: opendap
    dataset_link: 'https://ecat.ga.gov.au/geonetwork/srv/eng/catalog.search#/metadata/{metadata_uuid}'
    colormap_name: rainbow
    color_count: 256
    timestamp_detail_view: true
    wms_layer_name: rad_th_equiv_conc
    wms_color_range: [0, 40]
    wms_pixel_size: 0.01
  uranium_grids:
    dataset_format: grid
    min_polygon_bbox_width: 180.0 # maximum bounding box width for detailed display. Uses survey convex-hull polygons for anything larger.
    keyword_list: [NCI, geophysical survey, airborne digital data, radiometrics, uranium, grid]
    dataset_type_name: Uranium Equivalent Survey grids
    netcdf_path_prefix: null #C:\Temp\Geophysics\radiometric grids # Local directory containing files. Use null to use OPeNDAP
    polygon_color: ff800080 # Purple
    polygon_outline: 1
    protocol: opendap
    dataset_link: 'https://ecat.ga.gov.au/geonetwork/srv/eng/catalog.search#/metadata/{metadata_uuid}'
    colormap_name: rainbow
    color_count: 256
    timestamp_detail_view: true
    wms_layer_name: rad_u_equiv_conc
    wms_color_range: [0, 10]
    wms_pixel_size: 0.01
  magnetic_lines:
    dataset_format: line
    min_polygon_bbox_width: 0.5 # maximum bounding box width for detailed display. Uses survey convex-hull polygons for anything larger.
    keyword_list: [line, TMI, magnetic, airborne, geophysics]
    dataset_type_name: Magnetic Line Surveys
    netcdf_path_prefix: null #C:\Temp\Geophysics\magnetic_line # Local directory containing files. Use null to use OPeNDAP
    polygon_color: ffff0000 # Blue
    polygon_outline: 1
    line_color: ffff0000 # Blue
    line_width: 5
    protocol: opendap
    dataset_link: http://dapds00.nci.org.au/thredds/catalog/uc0/rr2_dev/axi547/magnetic_line/catalog.html?dataset=uc0/rr2_dev/axi547/magnetic_line/{netcdf_basename}
    height_variable: null # Do not set this value for 2D coordinates
    colormap_name: rainbow
    color_count: 256
    timestamp_detail_view: true
  radiometric_lines:
    dataset_format: line
    min_polygon_bbox_width: 0.5 # maximum bounding box width for detailed display. Uses survey convex-hull polygons for anything larger.
    keyword_list: [line, radiometrics, airborne, geophysics]
    dataset_type_name: Radiometric Line Surveys
    netcdf_path_prefix: null #C:\Temp\Geophysics\radiometric_line # Local directory containing files. Use null to use OPeNDAP
    polygon_color: ff800080 # Purple
    polygon_outline: 1
    line_color: ff800080 # Purple
    line_width: 5
    protocol: opendap
    dataset_link: http://dapds00.nci.org.au/thredds/catalog/uc0/rr2_dev/axi547/radiometric_line/catalog.html?dataset=uc0/rr2_dev/axi547/radiometric_line/{netcdf_basename}
    height_variable: null # Do not set this value for 2D coordinates
    colormap_name: rainbow
    color_count: 256
    timestamp_detail_view: true
    
 